# Mike McQuade
# amino-acid-frequency.pl
use strict;
use warnings;

# Initialize the variables
my ($a,$c,$g,$t);
$a = $c = $g = $t = 0;
my $string = "ACTTAGCCTACCGCAGTCTCATCTCAGGAGGGAACGGATGTCGATCGGGTGCTGTTTTGTATGGGCGGCTTCGTGTGACTATCTTGTCGGTCTCTATTGGATTCACTTTATTAACCACACCGAGGCCGTCGCTGGCATACCGTGGGTAGTCAATCCCCGATATAACACGCATAATATTATAGTAATGTTCGTCAGAGTAAAAGTGCTATTTTCGTTTACGGGGAGTTAACAGGTTGGAATCAGCGGCGGACTTCATTTTGATTGTGTTGTCCTTTTATTTCAGATTCCCACGGGGCACTTAGCCCATTGCGAGACGGTTCACCTTGAAAACAATCGAGAATGTAGGTGGGCTGTAGAACAGGGAGTGCGCATTCGACCGTCGATCAGTTCCACCAGGAACGATTTGATTAAGGTGGTTTAGATGTAAGTTAGAGAAAAGGGAGGGTTAGTCTTGCTTAGATCTGCTCAACACGGTTCTGCGTGCTCAAATGTGTTGCAGAAGGCCAAGGCAGTAAATCGTTTGGGCGGTCCCTGGCAGCTAACTGTGCTCGCGACATCTGTCCATTCATCCGGAGACATATAAACCAGCAGGTTCATTTCGTTTCGTTATGGCAAGAATGTCCGACACCAAAGTCCGTGACACGATGCTGTCGAAACGGTTGTACGTAATCGGTACGTCATTAGGGCCGTTATAGGCCTCTGCGTAGAGCAGTATCACAGGAGACCCAGTCTCAGATCCATTTTCCCCCCAAGTAAGGGGGAAGTTACAATTTGAGTAGGGGGACAATAGTCCAGGAGTCAGGTACTGTCAGGGACGTGTCACGCGCGCAGTGCTCCGGTCAGTATCTTTCGACGGGACCCCGACTATAAAATTGCTACGCCGTGATCGGATTAACAGACTAGTAAATTAGCGGCTTGACCCATCGAACGCTTCGGCTCTTCCATGACAGCCTCCGGTCTACGGCTAAA";

# Count how many of each letter is in the string
for (my $i = 0; $i < length($string); $i++) {
	if (substr($string,$i,1) eq 'A') {$a++;}
	elsif (substr($string,$i,1) eq 'C') {$c++;}
    elsif (substr($string,$i,1) eq 'G') {$g++;}
	elsif (substr($string,$i,1) eq 'T') {$t++;}
}

# Print out the number of each letter
print $a." ".$c." ".$g." ".$t."\n";